# Generated by Django 5.0.6 on 2024-06-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('useremail', models.CharField(max_length=200)),
                ('usermobile', models.IntegerField()),
                ('userpassword', models.CharField(max_length=200)),
            ],
        ),
    ]
