# Generated by Django 5.0.6 on 2024-06-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userdetails',
            new_name='Userdetailss',
        ),
    ]
