# Generated by Django 5.0.6 on 2024-06-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cardetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=200)),
                ('carmodel', models.CharField(max_length=200)),
                ('caryear', models.CharField(max_length=200)),
                ('carprice', models.CharField(max_length=200)),
                ('carmlg', models.CharField(max_length=200)),
                ('carphoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
